#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
from os.path import split
import argparse
import pandas as pd
from datetime import date


# Import from hello_world
import apirestoolbox
from apirestoolbox.lib import daily_forecast


daily_forecast("742676", date.today().year,
               date.today().month, date.today().day)
